CREATE TABLE users (
    id INT AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(200) NOT NULL,
    name VARCHAR(200) NOT NULL,
    password TEXT NOT NULL,
    PRIMARY KEY (id)
);
